# Generated by Django 5.2.5 on 2025-10-17 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_voicecall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicecall',
            name='participants',
        ),
        migrations.AlterField(
            model_name='voicecall',
            name='channel_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='voicecall',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_calls', to=settings.AUTH_USER_MODEL),
        ),
    ]
